
          version: '3'
          services:
            prometheus:
              build: .
              ports:
                - "9090:9090"
              volumes:
                - /* I will hide this for now for security reasons /*
