          global:
            scrape_interval: 15s
          
          scrape_configs:
            - job_name: 'node'
              static_configs:
                - targets: [''] # I will hide my IP address for the time being 
